services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP-Port for Communication
      - "15672:15672"  # Management-Port for Web Console
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s   # check every 10 sec
      timeout: 5s     # wait 5 s
      retries: 10     # max 10 retries
      start_period: 20s  # give him 20s
    networks:
      - app-network

  chatapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    depends_on:
      rabbitmq:
        condition: service_healthy 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
